// <auto-generated />
using System;
using Maliev.CustomerService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.CustomerService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260516011634_AddCustomerLifecycleStatus")]
    partial class AddCustomerLifecycleStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(5);

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnOrder(6);

                    b.Property<string>("AddressLine3")
                        .HasColumnType("text")
                        .HasColumnOrder(7);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(9);

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(12);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(13);

                    b.Property<string>("District")
                        .HasColumnType("text")
                        .HasColumnOrder(8);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnOrder(4);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(2);

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(1);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(11);

                    b.Property<string>("RecipientName")
                        .HasColumnType("text");

                    b.Property<string>("RecipientPhone")
                        .HasColumnType("text");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(10);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(14);

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_address_country_id");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("ix_address_owner_type_owner_id");

                    b.ToTable("Addresses", t =>
                        {
                            t.HasCheckConstraint("ck_address_owner_type", "\"OwnerType\" IN ('Customer', 'Company')");

                            t.HasCheckConstraint("ck_address_type", "\"Type\" IN ('Billing', 'Shipping')");
                        });
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BdexVerificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BusinessObjectives")
                        .HasColumnType("text");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("text");

                    b.Property<string>("CompanyStatusNameTh")
                        .HasColumnType("text");

                    b.Property<string>("CompanyTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentYearOrderCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("CurrentYearPurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullNameTh")
                        .HasColumnType("text");

                    b.Property<bool>("IsVerifiedFromBdex")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StockSymbol")
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TierCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Tier");

                    b.HasIndex("VatNumber")
                        .IsUnique()
                        .HasFilter("\"VatNumber\" IS NOT NULL");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.CompanyDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyDocuments");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.CompanyTierSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CoinRewardPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("FreeShippingMinOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinOrderCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinPurchaseValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TierName");

                    b.HasIndex("TierName", "ValidFrom");

                    b.ToTable("CompanyTierSettings");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommunicationPreferences")
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Extension")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryContact")
                        .HasColumnType("boolean");

                    b.Property<string>("Landline")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Due on receipt");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("Active");

                    b.Property<string>("ThaiNationalId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UsesCompanyBillingAddress")
                        .HasColumnType("boolean");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AccountManagerEmployeeId")
                        .HasDatabaseName("ix_customers_account_manager_employee_id");

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "ix_customer_email_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Email" }, "ix_customer_email_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Email" }, "ix_customer_email_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "FirstName" }, "ix_customer_first_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "FirstName" }, "ix_customer_first_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "FirstName" }, "ix_customer_first_name_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "LastName" }, "ix_customer_last_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "LastName" }, "ix_customer_last_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "LastName" }, "ix_customer_last_name_trgm"), new[] { "gin_trgm_ops" });

                    b.HasIndex(new[] { "Email" }, "ix_customers_email_unique")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("PrincipalId")
                        .IsUnique();

                    b.ToTable("CustomerAccounts");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.DocumentReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_reference");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("filename");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<string>("SignedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("signed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("document_references");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.InternalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("note_text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("owner_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.ToTable("internal_notes");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.InternalNoteComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by_name");

                    b.Property<Guid>("InternalNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_note_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InternalNoteId");

                    b.ToTable("internal_note_comments");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.NDARecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DocumentReferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("NDARecords");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.PaymentTerm", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DiscountDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<int?>("DueDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TypicalUse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Code");

                    b.ToTable("PaymentTerms");

                    b.HasData(
                        new
                        {
                            Code = "DUE_ON_RECEIPT",
                            Category = "Immediate",
                            Description = "Payment is due as soon as the invoice is received.",
                            DueDays = 0,
                            IsDefault = true,
                            Name = "Due on receipt",
                            SortOrder = 0,
                            TypicalUse = "Use for one-off jobs, quick-turnaround work, or customers without approved credit."
                        },
                        new
                        {
                            Code = "PREPAID",
                            Category = "Advance",
                            Description = "Full payment is required before work starts or goods are released.",
                            DueDays = 0,
                            IsDefault = false,
                            Name = "Prepaid",
                            SortOrder = 5,
                            TypicalUse = "Use for new customers, high-risk accounts, custom materials, or orders that require committed cash before production."
                        },
                        new
                        {
                            Code = "CASH_WITH_ORDER",
                            Category = "Advance",
                            Description = "Payment is collected when the order is placed.",
                            DueDays = 0,
                            IsDefault = false,
                            Name = "Cash with order",
                            SortOrder = 10,
                            TypicalUse = "Use for ecommerce-like orders, small standard items, or orders that should not enter production without payment."
                        },
                        new
                        {
                            Code = "CASH_ON_DELIVERY",
                            Category = "Delivery",
                            Description = "Payment is collected when goods are delivered.",
                            DueDays = 0,
                            IsDefault = false,
                            Name = "Cash on delivery",
                            SortOrder = 15,
                            TypicalUse = "Use for local delivery or pickup workflows where collection happens at handoff instead of at invoice issue."
                        },
                        new
                        {
                            Code = "FIFTY_DEPOSIT_BALANCE_BEFORE_SHIP",
                            Category = "Deposit",
                            Description = "The customer pays 50% before production and the remaining 50% before shipment.",
                            IsDefault = false,
                            Name = "50% deposit, balance before shipment",
                            SortOrder = 20,
                            TypicalUse = "Use for custom manufacturing, special-order materials, tooling, and larger jobs where MALIEV should not carry the full working-capital risk."
                        },
                        new
                        {
                            Code = "NET_7",
                            Category = "Net",
                            Description = "Full invoice amount is due 7 calendar days after the invoice date.",
                            DueDays = 7,
                            IsDefault = false,
                            Name = "Net 7",
                            SortOrder = 25,
                            TypicalUse = "Use for newer accounts or small businesses where cash collection should stay tight but short trade credit is acceptable."
                        },
                        new
                        {
                            Code = "NET_10",
                            Category = "Net",
                            Description = "Full invoice amount is due 10 calendar days after the invoice date.",
                            DueDays = 10,
                            IsDefault = false,
                            Name = "Net 10",
                            SortOrder = 30,
                            TypicalUse = "Use for short trade-credit arrangements where the customer needs processing time but not a full month."
                        },
                        new
                        {
                            Code = "NET_15",
                            Category = "Net",
                            Description = "Full invoice amount is due 15 calendar days after the invoice date.",
                            DueDays = 15,
                            IsDefault = false,
                            Name = "Net 15",
                            SortOrder = 35,
                            TypicalUse = "Use for repeat customers with modest credit exposure or jobs where two-week payment is commercially acceptable."
                        },
                        new
                        {
                            Code = "NET_30",
                            Category = "Net",
                            Description = "Full invoice amount is due 30 calendar days after the invoice date.",
                            DueDays = 30,
                            IsDefault = false,
                            Name = "Net 30",
                            SortOrder = 40,
                            TypicalUse = "Use as the standard B2B trade-credit term for approved customers with normal purchasing cycles."
                        },
                        new
                        {
                            Code = "NET_45",
                            Category = "Net",
                            Description = "Full invoice amount is due 45 calendar days after the invoice date.",
                            DueDays = 45,
                            IsDefault = false,
                            Name = "Net 45",
                            SortOrder = 45,
                            TypicalUse = "Use for larger commercial customers that require longer internal approval cycles."
                        },
                        new
                        {
                            Code = "NET_60",
                            Category = "Net",
                            Description = "Full invoice amount is due 60 calendar days after the invoice date.",
                            DueDays = 60,
                            IsDefault = false,
                            Name = "Net 60",
                            SortOrder = 50,
                            TypicalUse = "Use only for established enterprise or government accounts where longer credit has been approved."
                        },
                        new
                        {
                            Code = "NET_90",
                            Category = "Net",
                            Description = "Full invoice amount is due 90 calendar days after the invoice date.",
                            DueDays = 90,
                            IsDefault = false,
                            Name = "Net 90",
                            SortOrder = 55,
                            TypicalUse = "Use sparingly for strategic enterprise agreements because it materially increases working-capital exposure."
                        },
                        new
                        {
                            Code = "END_OF_MONTH",
                            Category = "Calendar",
                            Description = "Payment is due by the last day of the month in which the invoice is issued.",
                            IsDefault = false,
                            Name = "End of month",
                            SortOrder = 60,
                            TypicalUse = "Use when the customer pays all invoices in a monthly closing cycle."
                        },
                        new
                        {
                            Code = "NET_30_EOM",
                            Category = "Calendar",
                            Description = "Payment is due 30 days after the end of the invoice month.",
                            IsDefault = false,
                            Name = "Net 30 EOM",
                            SortOrder = 65,
                            TypicalUse = "Use for customers whose accounts payable process calculates due dates from month-end rather than invoice date."
                        },
                        new
                        {
                            Code = "NET_60_EOM",
                            Category = "Calendar",
                            Description = "Payment is due 60 days after the end of the invoice month.",
                            IsDefault = false,
                            Name = "Net 60 EOM",
                            SortOrder = 70,
                            TypicalUse = "Use for approved enterprise accounts with month-end plus extended credit cycles."
                        },
                        new
                        {
                            Code = "FIFTEENTH_PROXIMO",
                            Category = "Calendar",
                            Description = "Payment is due on the 15th day of the month after the invoice month.",
                            IsDefault = false,
                            Name = "15th of following month",
                            SortOrder = 75,
                            TypicalUse = "Use for customers that run a fixed mid-month payment cycle."
                        },
                        new
                        {
                            Code = "ONE_TEN_NET_30",
                            Category = "Discount",
                            Description = "Customer may deduct 1% if payment is received within 10 days; otherwise the full amount is due in 30 days.",
                            DiscountDays = 10,
                            DiscountPercent = 1m,
                            DueDays = 30,
                            IsDefault = false,
                            Name = "1/10 Net 30",
                            SortOrder = 80,
                            TypicalUse = "Use when a small early-payment incentive helps improve cash flow without heavily discounting margin."
                        },
                        new
                        {
                            Code = "TWO_TEN_NET_30",
                            Category = "Discount",
                            Description = "Customer may deduct 2% if payment is received within 10 days; otherwise the full amount is due in 30 days.",
                            DiscountDays = 10,
                            DiscountPercent = 2m,
                            DueDays = 30,
                            IsDefault = false,
                            Name = "2/10 Net 30",
                            SortOrder = 85,
                            TypicalUse = "Use for approved accounts where faster cash collection is worth the discount."
                        },
                        new
                        {
                            Code = "TWO_TEN_NET_60",
                            Category = "Discount",
                            Description = "Customer may deduct 2% if payment is received within 10 days; otherwise the full amount is due in 60 days.",
                            DiscountDays = 10,
                            DiscountPercent = 2m,
                            DueDays = 60,
                            IsDefault = false,
                            Name = "2/10 Net 60",
                            SortOrder = 90,
                            TypicalUse = "Use for large accounts that require longer net terms but can be encouraged to pay early."
                        },
                        new
                        {
                            Code = "MILESTONE_PROGRESS",
                            Category = "Milestone",
                            Description = "Invoices are issued and paid as agreed project milestones are completed.",
                            IsDefault = false,
                            Name = "Milestone / progress payments",
                            SortOrder = 95,
                            TypicalUse = "Use for long-running engineering, tooling, fabrication, or project work where billing should follow delivery phases."
                        },
                        new
                        {
                            Code = "INSTALLMENTS",
                            Category = "Installment",
                            Description = "Payment is split into scheduled installments instead of one invoice due date.",
                            IsDefault = false,
                            Name = "Installments",
                            SortOrder = 100,
                            TypicalUse = "Use for high-value projects with a negotiated payment schedule that should be documented on the quote or contract."
                        });
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.CompanyDocument", b =>
                {
                    b.HasOne("Maliev.CustomerService.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.CustomerAccount", b =>
                {
                    b.HasOne("Maliev.CustomerService.Domain.Entities.Customer", "Customer")
                        .WithOne()
                        .HasForeignKey("Maliev.CustomerService.Domain.Entities.CustomerAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Maliev.CustomerService.Domain.Entities.InternalNoteComment", b =>
                {
                    b.HasOne("Maliev.CustomerService.Domain.Entities.InternalNote", "Note")
                        .WithMany()
                        .HasForeignKey("InternalNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });
#pragma warning restore 612, 618
        }
    }
}
